
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 16 19:11:48 ICT 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface SimpleCSym {
  /* terminals */
  public static final int MINUS = 7;
  public static final int DIVIDE = 9;
  public static final int EOF = 0;
  public static final int PLUS = 6;
  public static final int ABS = 11;
  public static final int PERIOD = 10;
  public static final int error = 1;
  public static final int RPAREN = 4;
  public static final int SEMICOLON = 5;
  public static final int TIMES = 8;
  public static final int INTLITERAL = 2;
  public static final int LPAREN = 3;
}

